service: nudge
frameworkVersion: ">=1.11.0 <2.0.0"
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  versionFunctions: false
  environment:
    SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}

plugins:
  - serverless-offline

functions:
  buildkite:
    handler: src/handlers/buildkite.handler
    events:
      - http:
          path: buildkite
          method: post