service: nudge
frameworkVersion: ">=1.11.0 <2.0.0"
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  versionFunctions: false
  environment:
    DUMMY_EMAIL: ${env:DUMMY_EMAIL}
    SLACK_TOKEN: ${env:SLACK_TOKEN}

plugins:
  - serverless-offline

functions:

  buildkiteAuthorizer:
    handler: src/authorizers/buildkite.handler

  buildkite:
    handler: src/handlers/buildkite.handler
    events:
      - http:
          path: buildkite
          method: post
          cors: true
          authorizer:
            name: buildkiteAuthorizer
            type: request
            identitySource: method.request.header.X-Buildkite-Token


  githubAuthorizer:
    handler: src/authorizers/github.handler

  github:
    handler: src/handlers/github.handler
    events:
      - http:
          path: github
          method: post
